apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::372572312003:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1NMR4F1LGTJ3N
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::372572312003:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-08-14T21:45:55Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "3267"
  uid: f6f64059-c7ad-4da5-9e76-74af7f538c25
