apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::372572312003:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-13ZZ81JGJK49A
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::372572312003:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-08-14T23:47:51Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1815"
  uid: 19d74aed-427d-47e2-ba8c-f3c7416f384d
